import { GoalItem, MemoryItem, ProjectItem, TaskItem, UserProfile, WeeklyReview } from '../types';

export const DEFAULT_USER_PROFILE: UserProfile = {
  nome: 'Wesley Gomes',
  comoSerChamado: 'Wesley',
  rotinaAtual: 'Profissional: Atualização matinal do CRM da INC Empreendimentos, ligações para novos leads, retrabalho de carteira antiga e agendamento de visitas. Pessoal: Treinos de manhã e tempo presente com a família à noite.',
  responsabilidades: 'Profissional: Corretor de Imóveis na INC Empreendimentos, gestão do funil no CRM, qualificação de leads, negociações e fechamento de vendas. Pessoal: Saúde, finanças da família, pai e marido presente.',
  metasProximas: 'Alcançar média de 10 vendas por mês até o final do ano na INC Empreendimentos; perder peso e criar rotina de saúde consistente; quitar pendências e organizar investimentos familiares.',
  metasLongoPrazo: 'Construir processo comercial previsível e automatizado com IA; atingir independência financeira com patrimônio imobiliário; ser um pai e marido em constante evolução com propósito de vida.',
  mudancasDesejadas: 'Evitar que o trabalho tome conta de todo o tempo, ter mais disciplina diária, priorização clara e constante constância nos hábitos saudáveis.',
  projetosAtuais: 'Aumento da Conversão CRM (INC Empreendimentos), Reativação de Carteira Antiga de Leads, Projeto Saúde & Emagrecimento, Organização de Finanças Familiares.',
  ideiasFuturas: 'Uso de IA para geração de scripts de atendimento personalizados para corretores e canal de prospecção passiva.',
  prioridades: '1. Atendimento ágil e conversão no CRM INC | 2. Saúde e perda de peso | 3. Tempo de qualidade com a família | 4. Estudo contínuo de IA e Negociação.',
  organizacaoHoje: 'Uso de CRM comercial, listas de tarefas diárias e blocos de tempo.',
  dificuldades: 'Gargalos no retrabalho de volume grande de leads antigos e manutenção do equilíbrio trabalho/família sem ansiedade.',
  procrastination: 'Dispersão durante o preenchimento de histórico de mensagens no CRM e oscilação na constância dos hábitos de saúde.',
  estudando: 'Técnicas de Negociação Imobiliária, Inteligência Artificial para Produtividade e Educação Financeira.',
  querAprender: 'Automação comercial com IA, Engenharia de Prompt para vendas e Estratégias Avançadas de Atendimento.',
  rotinaSaude: 'Caminhada/treino matinal 4x por semana e dieta focada em perda de peso e energia.',
  habitosMelhorar: 'Manter disciplina constante nos treinos, organizar follow-ups do CRM antes do almoço e desconectar o celular à noite.',
  objetivosFinanceiros: 'Quitar pendências, consolidar reserva de emergência e aportar 30% das comissões em investimentos duradouros.',
  planejamentoFinancas: 'Aporte sistemático pós-fechamento de vendas na INC e orçamento familiar controlado.',
  interviewCompleted: true,
  currentInterviewStep: 7,
};

export const INITIAL_MEMORIES: MemoryItem[] = [
  {
    id: 'mem-1',
    categoria: 'identidade',
    titulo: 'Visão Dual: Wesley Gomes (Pessoal & Profissional)',
    conteudo: 'Wesley Gomes busca construir uma vida com propósito. Na INC Empreendimentos é corretor focado em alta conversão e previsibilidade de vendas. No pessoal, busca ser um pai/marido presente, com saúde física excelente, organização financeira e evolução contínua com IA.',
    importancia: 'alta',
    data: new Date().toISOString(),
    origin: 'interview',
  },
  {
    id: 'mem-2',
    categoria: 'metas',
    titulo: 'Meta Profissional Principal: 10 Vendas/Mês na INC',
    conteudo: 'Construir um processo comercial previsível para alcançar a média de 10 vendas de imóveis por mês até o final do ano, otimizando o funil (Lead → Atendimento → Visita → Venda).',
    importancia: 'alta',
    data: new Date().toISOString(),
    origin: 'interview',
  },
  {
    id: 'mem-3',
    categoria: 'rotina',
    titulo: 'Gestão de Leads & Retrabalho no CRM (INC)',
    conteudo: 'Rotina comercial focada em priorizar clientes quentes, organizar follow-ups diários sem perder oportunidades e executar retrabalho estruturado da carteira de leads antigos.',
    importancia: 'alta',
    data: new Date().toISOString(),
    origin: 'interview',
  },
  {
    id: 'mem-4',
    categoria: 'saude',
    titulo: 'Saúde & Perda de Peso (Wesley Pessoal)',
    conteudo: 'Objetivo de perder peso, adquirir hábitos alimentares saudáveis e manter consistência diária em atividades físicas para alta energia física e mental.',
    importancia: 'alta',
    data: new Date().toISOString(),
    origin: 'interview',
  },
  {
    id: 'mem-5',
    categoria: 'financas',
    titulo: 'Organização Financeira & Patrimônio Familiar',
    conteudo: 'Quitar pendências, estruturar base financeira sólida e aportar 30% de cada comissão de vendas na INC em reserva e investimentos de longo prazo.',
    importancia: 'alta',
    data: new Date().toISOString(),
    origin: 'interview',
  },
  {
    id: 'mem-6',
    categoria: 'relacoes',
    titulo: 'Família & Tempo de Qualidade Presente',
    conteudo: 'Preservar as noites e os fins de semana para estar 100% presente com a família (esposa e filhos), mantendo equilíbrio entre trabalho e vida pessoal.',
    importancia: 'alta',
    data: new Date().toISOString(),
    origin: 'interview',
  },
  {
    id: 'mem-7',
    categoria: 'aprendizado',
    titulo: 'Evolução Tecnológica & Inteligência Artificial',
    conteudo: 'Estudo constante de ferramentas de IA para aumentar a produtividade no trabalho, aprimorar scripts de atendimento e expandir a capacidade de pensamento estratégico.',
    importancia: 'media',
    data: new Date().toISOString(),
    origin: 'interview',
  },
  {
    id: 'mem-8',
    categoria: 'ideias',
    titulo: 'Wesley Direção: Princípios & Propósito de Vida',
    conteudo: 'Fazer as coisas certas mantendo equilíbrio entre trabalho, família, saúde, aprendizado e crescimento pessoal. Fazer escolhas estratégicas sem se perder no excesso de tarefas operacionais.',
    importancia: 'alta',
    data: new Date().toISOString(),
    origin: 'interview',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    titulo: 'Atualizar CRM da INC e priorizar leads quentes do dia',
    prioridade: 'urgente',
    concluida: false,
    data: new Date().toISOString().split('T')[0],
    categoria: 'rotina',
    notas: 'Profissional: Triagem rápida de oportunidades com maior probabilidade de visita.',
  },
  {
    id: 'task-2',
    titulo: 'Fazer 15 contatos de retrabalho com carteira antiga do CRM',
    prioridade: 'urgente',
    concluida: false,
    data: new Date().toISOString().split('T')[0],
    categoria: 'projetos',
    notas: 'Profissional: Reaquecer leads da INC Empreendimentos usando novo script de abordagem.',
  },
  {
    id: 'task-3',
    titulo: 'Confirmar horários de visitas presenciais agendadas para o fim de semana',
    prioridade: 'importante',
    concluida: false,
    data: new Date().toISOString().split('T')[0],
    categoria: 'metas',
    notas: 'Profissional: Avançar etapa de visitas para bater meta mensal.',
  },
  {
    id: 'task-4',
    titulo: 'Treino de cardio/musculação matinal (Perda de peso)',
    prioridade: 'importante',
    concluida: true,
    data: new Date().toISOString().split('T')[0],
    categoria: 'saude',
    notas: 'Pessoal: Consistência de saúde e disposição física.',
  },
  {
    id: 'task-5',
    titulo: 'Revisar orçamento mensal e planejar aporte da próxima comissão',
    prioridade: 'importante',
    concluida: false,
    data: new Date().toISOString().split('T')[0],
    categoria: 'financas',
    notas: 'Pessoal: Manter finanças familiares organizadas.',
  },
  {
    id: 'task-6',
    titulo: 'Jantar sem celular e tempo de qualidade com a família',
    prioridade: 'importante',
    concluida: false,
    data: new Date().toISOString().split('T')[0],
    categoria: 'relacoes',
    notas: 'Pessoal: Desconexão do trabalho e presença familiar.',
  },
];

export const INITIAL_GOALS: GoalItem[] = [
  {
    id: 'goal-1',
    objetivo: '[Profissional] Atingir Média de 10 Vendas/Mês na INC Empreendimentos',
    prazo: '2026-12-31',
    progresso: 60,
    proximosPassos: [
      'Manter média diária de 20 contatos qualificados no CRM',
      'Refinar scripts de atendimento e contorno de objeções com IA',
      'Garantir taxa de agendamento de ao menos 5 visitas presenciais por semana',
    ],
    categoria: 'metas',
    dataCriacao: new Date().toISOString().split('T')[0],
    status: 'em_andamento',
  },
  {
    id: 'goal-2',
    objetivo: '[Pessoal] Saúde Física: Perda de Peso & Hábitos Saudáveis',
    prazo: '2026-11-30',
    progresso: 50,
    proximosPassos: [
      'Manter 4 a 5 treinos semanais de exercício físico',
      'Seguir plano alimentar focado em déficit calórico e energia',
      'Monitorar peso e medidas quinzenalmente',
    ],
    categoria: 'saude',
    dataCriacao: new Date().toISOString().split('T')[0],
    status: 'em_andamento',
  },
  {
    id: 'goal-3',
    objetivo: '[Pessoal] Quitar Pendências & Construir Reserva de Emergência',
    prazo: '2026-10-31',
    progresso: 70,
    proximosPassos: [
      'Destinar 30% de cada comissão das vendas da INC para os aportes',
      'Manter custo de vida controlado sem gastos impulsivos',
    ],
    categoria: 'financas',
    dataCriacao: new Date().toISOString().split('T')[0],
    status: 'em_andamento',
  },
];

export const INITIAL_PROJECTS: ProjectItem[] = [
  {
    id: 'proj-1',
    nome: '[Profissional] Otimização de Funil & Retrabalho CRM (INC)',
    descricao: 'Estruturação da rotina comercial para transformar alto volume de leads em visitas e contratos fechados.',
    prioridade: 'alta',
    progresso: 75,
    status: 'ativo',
    tarefasRelacionadas: ['task-1', 'task-2', 'task-3'],
    dataAtualizacao: new Date().toISOString().split('T')[0],
  },
  {
    id: 'proj-2',
    nome: '[Pessoal] Programa de Saúde, Perda de Peso & Vitalidade',
    descricao: 'Foco contínuo em hábitos saudáveis, reeducação alimentar e rotina matinal de exercícios.',
    prioridade: 'alta',
    progresso: 65,
    status: 'ativo',
    dataAtualizacao: new Date().toISOString().split('T')[0],
  },
  {
    id: 'proj-3',
    nome: '[Pessoal] Gestão Financeira Familiar & Estudos de IA',
    descricao: 'Organização patrimonial da família e aplicação prática de IA no dia a dia para produtividade.',
    prioridade: 'media',
    progresso: 70,
    status: 'ativo',
    dataAtualizacao: new Date().toISOString().split('T')[0],
  },
];

export const INITIAL_WEEKLY_REVIEWS: WeeklyReview[] = [
  {
    id: 'review-1',
    semana: 'Semana 31 (2026)',
    conquistas: [
      'Processou 100% dos leads novos no CRM da INC Empreendimentos',
      'Fez 40 contatos de retrabalho com clientes antigos e agendou 4 visitas',
      'Manteve 4 treinos físicos na semana e refeições saudáveis organizadas',
      'Preservou noites sem interrupções de trabalho com a família',
    ],
    pendencias: [
      'Refinar o script de recontato no WhatsApp para leads que esfriaram',
      'Organizar planilha de acompanhamento dos aportes de comissão',
    ],
    pontosAtencao: [
      'Gargalo no tempo gasto digitando históricos longos no CRM',
      'Cuidado para não deixar reuniões comerciais invadirem o horário da janta em família',
    ],
    recomendacoes: [
      'Fazer bloco focado de ligações de retrabalho entre 10h e 11h30',
      'Usar a IA do RAXXER para gerar respostas personalizadas e contornar objeções rapidamente',
      'Bloquear a agenda a partir das 19h para foco exclusivo na família',
    ],
    data: new Date().toISOString(),
  },
];
